### ISSUE TITLE
PV360v3.1.

### ISSUE THREAD

**Issue by karthikc777** [BrkRaw/brkraw#79] opened 2022-01-12 15:27 UTC
Hi all!

**Is your feature request related to a problem? Please describe.**
I have data-sets from PV360v2.0 and PV360v3.1. I was able to successfully read and write data from PV360v2.0 data. However, there's an error reading v3.1 data. Could you please advise? 

![PV360_v3 1_Error](https://user-images.githubusercontent.com/10176886/149168091-2d42086b-2bae-45c5-8925-5ced7876eac2.png)

Many thanks!

**Comment by grandjeanlab** [comment] 2022-01-13 11:09
I think pull request #80 solves this for PV360 v3. can I let you check or upload the pv360v3 dataset so I can check?

**Comment by karthikc777** [comment] 2022-01-13 14:12
Thanks, I will check and let you know.

**Comment by dvm-shlee** [comment] 2022-01-13 16:40
@grandjeanlab Thank you, your pull request has been merged!, @karthikc777 Please let me know if you are still having issues.

**Comment by karthikc777** [comment] 2022-01-14 15:07
Hello, 

I still have the same issue. Could you please have a look? Please find the link to the data below:
https://drive.google.com/file/d/11NbohJji_-GpLYIa7lbmgFwojP1Lh7F_/view?usp=sharing

Thanks!

**Comment by grandjeanlab** [comment] 2022-01-17 09:14
it works for me when I delete folder `99999`. This is a picture of the craddle before animal entry into the bore? it seems to confuse `brkraw`.  Maybe an issue that can be filtered out @dvm-shlee ?

Also, make sure you get a fresh install of brkraw from github `pip install git+https://github.com/brkraw/brkraw`

I ran: `brkraw  bids_helper ./ pv360` and `brkraw  bids_convert ./ pv360.xlsx`

and get `tree Data`

Data
|-- README
|-- dataset_description.json
|-- participants.json
|-- participants.tsv
`-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1
    `-- anat
        |-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-01_T2w.nii.gz
        |-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-02_T2w.nii.gz
        |-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-03_T2w.nii.gz
        |-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-04_T2w.nii.gz
        |-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-05_T2w.nii.gz
        `-- sub-RUnderscorebrb37UnderscoreM20UnderscoreKSPB28.3dUnderscoreScanUnderscore1_run-06_T2w.nii.gz

**Comment by karthikc777** [comment] 2022-01-17 18:21
Thanks for checking the data. I have installed a fresh version(v0.3.7), deleted the 9999 folder but I'm getting a different error 'name multi_session not defined' on both PV360v2 and v3.1. Please see below the screenshot
![error](https://user-images.githubusercontent.com/10176886/149820752-7c1a8f59-f261-46c3-9ad3-507cc3f49eb2.png)
Thanks!

**Comment by grandjeanlab** [comment] 2022-01-18 10:09
super weird. I get the same error when I  user

pip install git+https://github.com/brkraw/brkraw

but the issue isn't there when I pip install from my forked version. 

pip install git+https://github.com/grandjeanlab/brkraw

Would you mind trying?

**Comment by karthikc777** [comment] 2022-01-18 11:51
I've had a go and it's working now! 

Many thanks!

**Comment by grandjeanlab** [comment] 2022-01-18 12:56
@dvm-shlee , not sure what happened here. My fork should have been latest from brkraw and merge request should only have covered my commit on my fork..  any clue?

**Comment by dvm-shlee** [comment] 2022-02-02 18:30
@grandjeanlab @karthikc777 Just identify the origin of issues, de6cb1e will resolve the issue, please let me know if you still experiencing the same issue after patching this.

**Closed** 2022-02-03 00:55 UTC
