### ISSUE TITLE
Keep getting "TypeError: argument of type 'int' is not iterable"

### ISSUE THREAD

**Issue by johnjiang406** [BrkRaw/brkraw#98] opened 2022-11-04 14:36 UTC
Hi there,

Installed Brkraw on my Window10 PC. The installation was fine. But when running it, I keep getting the errors as below. Can anybody help? Thx a lot!

I have a full raw dataset in the path E:\raw\
![image](https://user-images.githubusercontent.com/117460646/200000154-8166cf4a-52d8-48f0-8d69-3cbffac0241e.png)

![image](https://user-images.githubusercontent.com/117460646/200001224-163fda79-2f0b-4e5a-96fd-5d28ffc20075.png)

**Comment by gdevenyi** [comment] 2022-11-04 15:00
Possibly related, https://github.com/BrkRaw/brkraw/issues/49

**Comment by johnjiang406** [comment] 2022-11-04 16:31
Thx for the super quick reply!

I carefully read the #49 and #80 and #66. Then, I downloaded the dataset in #66. It works well. 

So I tried the other data from my scanner. Found that some of them works, but some doesn't. My sanner use PV6.0.1. And I uploaded the "good" data here https://drive.google.com/file/d/1BMlb3cluK-9N8NUsnx_rmHn10MoiL1q6/view?usp=share_link.
And the "bad" data is here https://drive.google.com/file/d/1U1PgvzXUhDlVpi9SCcPjB909J_yVzBd4/view?usp=share_link.

Could anyone help test and tell why? I really appreciate it!

**Comment by grandjeanlab** [comment] 2023-01-25 11:07
interesting, I get the same error on one of my dataset with brkraw --version 0.3.7 
When I move to v0.3.8-rc1, I get a different issue (` ac_proc = visu_pars.parameters['VisuAcquisitionProtocol']` which I will raise as an issue if I can't solve it)

Interestingly, my student with version 0.3.6 (and python 3.7.9, anadonca 3 2021.05 go through my difficult without issue. 

See what kind of error when you `pip install git+https://github.com/brkraw/brkraw` to get the latest version of brkrw

**Comment by grandjeanlab** [comment] 2023-01-25 14:24
so, did some digging. 

with latest version installed from github with pip, I had the following error (see my comment above)

`Traceback (most recent call last):
  File "/home/traaffneu/joagra/.conda/envs/bruker_new/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/traaffneu/joagra/.conda/envs/bruker_new/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 321, in main
    if not is_localizer(dset, scan_id, reco_id):
  File "/home/traaffneu/joagra/.conda/envs/bruker_new/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 713, in is_localizer
    ac_proc = visu_pars.parameters['VisuAcquisitionProtocol']
KeyError: 'VisuAcquisitionProtocol'`

which seemed to be caused by dwi reconstructed imaged (pdata/1 and pdata/2). It gets corrected when I remove the PV6 reco. 

But at least the error message whichi got with brkraw 0.3.7 which was the same as @johnjiang406 got solved. if @johnjiang406  confirms, I think we can close this issue (and maybe open one about brkraw running into issues with reconstruction)

**Comment by dvm-shlee** [comment] 2023-07-01 18:24
#105 resolved this issue

**Closed by dvm-shlee** 2023-07-01 18:24 UTC
Labels: bug
