### ISSUE TITLE
Paravision 360.2

### ISSUE THREAD

**Issue by araikes** [BrkRaw/brkraw#49] opened 2021-04-29 21:26 UTC
**Is your feature request related to a problem? Please describe.**
I am attempting to convert a dataset (single mouse brain, including a T2 RARE and 3x diffusion EPI for the moment). The dataset is already unzipped (originally tar.gz file) so I was attempting to open the directory using the GUI and got the error below (except for "Exception in Tkinter callback" not present for command line). I get the same error on the command line. This was version invariant (tested using 0.3.3 and 0.3.6). This is in a dedicated conda environment with just the required packages + SimpleITK.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/ui/main_win.py", line 47, in open_dirdiag
    self._load_dataset()
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/ui/main_win.py", line 123, in _load_dataset
    self._raw = load(self._path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/__init__.py", line 8, in load
    return BrukerLoader(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/loader.py", line 93, in __init__
    self._pvobj = load(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/loader.py", line 21, in load
    return PvDatasetDir(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 145, in __init__
    self._parse_info()
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 160, in _parse_info
    if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

I additionally attempted the command line on the Zip file and received the following error regardless of GUI or command line (only difference is the "Exception in Tkinter callback")

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/ui/main_win.py", line 40, in open_filediag
    self._load_dataset()
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/ui/main_win.py", line 123, in _load_dataset
    self._raw = load(self._path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/__init__.py", line 8, in load
    return BrukerLoader(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/loader.py", line 93, in __init__
    self._pvobj = load(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/loader.py", line 24, in load
    return PvDatasetZip(path)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 205, in __init__
    self._parse_info()
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 236, in _parse_info
    self._acqp[scan_id] = Parameter(f.read().decode('UTF-8').split('\n'))
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/parser.py", line 7, in __init__
    self._set_param(*load_param(stringlist))
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/parser.py", line 44, in _set_param
    self._parameters[key] = convert_data_to(data, shape)
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/utils.py", line 98, in convert_data_to
    if any([',' in cell for cell in is_array]):
  File "/home/u26/adamraikes/.conda/envs/bruker/lib/python3.7/site-packages/brkraw/lib/utils.py", line 98, in <listcomp>
    if any([',' in cell for cell in is_array]):
TypeError: argument of type 'int' is not iterable
```
**Describe alternatives you've considered**
I suspect that this is a difference between folder structure for PV5/6 and PV360.2 (which we are running). Is there any way to make BrkRaw compatible with 360.2 data as well?

I can provide tarred datasets if helpful.

**Comment by gdevenyi** [comment] 2021-05-03 05:04
We would definitely welcome a complete example dataset to test against here. Otherwise, skipping the GUI and using the command line tools would be eliminate some unneeded complexity for testing.

**Comment by araikes** [comment] 2021-05-06 17:38
Hi @gdevenyi ,

Sorry for the lag on seeing this but thanks for getting back to me. Link to a Box folder with a tarred dataset for you to test with (representative of the majority of our datasets currently).

https://arizona.box.com/s/iseohu12gtc2llbsw94lzssvqulvt22a

Thanks

**Comment by gdevenyi** [comment] 2021-05-18 19:44
Thanks. We can compare this against existing datasets to figure things out.

Can you provide detail on exactly what it contains, so we can validate vs the info the brkraw converter provides?

**Comment by araikes** [comment] 2021-05-18 21:44
Oh yeah. I should've done that to begin with. There are 4 folders in that TAR file for a single mouse:

```
6/ - 3D RARE, 75 micron isotropic
8/ - Diffusion weighted sequence with 64 directions @ b = 1000 mm/s^2 , 8 b = 0 images at the beginning; 200 micron isotropic
9/ - Diffusion weighted sequence with 64 directions @ b = 2000 mm/s^2 , 8 b = 0 images at the beginning; 200 micron isotropic
10/ - Diffusion weighted sequence with 64 directions @ b = 3000 mm/s^2 , 8 b = 0 images at the beginning; 200 micron isotropic
```

Let me know what other info you might need.

**Comment by dvm-shlee** [comment] 2021-05-24 14:55
@araikes Hi, the main reason is the file you uploaded does not contain sufficient meta data files. I think this might be the issue related to the export function of Paravision 360?
Could you provide some information on how did you generate the 'tar' file?
The suggested way is to zip compress a whole raw-data folder with meta files located in the session root.

**Comment by araikes** [comment] 2021-05-24 16:08
Hi @dvm-shlee,

I will look into it. I haven't been the one generating the files. I'm just getting them downstream.

Can you provide me any information about what is missing from a meta-data so I can get with others about it?

Thanks again.

**Comment by dvm-shlee** [comment] 2021-05-24 16:34
@araikes 
![image](https://user-images.githubusercontent.com/7221078/119378295-1cd38680-bc8c-11eb-969e-6a111d0d6124.png)

The 'subject' file is the requirement to extract subject information.  The compression file you had shared seems not contain it. Is it the issue related to the Paravision 360? so don't have subject information on the data and instead keep it in database only?
![image](https://user-images.githubusercontent.com/7221078/119378522-55736000-bc8c-11eb-87f7-cdba126ee5b7.png)

**Comment by dvm-shlee** [comment] 2021-05-24 16:40
@gdevenyi How do you think about the raw data converting option 'without' subject file? Maybe return the error message? The subject file is one of the requirements to check '<brkraw obj>.is_pvdataset' became True. 

https://github.com/BrkRaw/bruker/blob/35b027aa493f647d1a50aace0568f68798363fee/brkraw/lib/loader.py#L95

**Comment by gdevenyi** [comment] 2021-05-26 14:09
I think we need to confirm what PV360, whether this is an accident or the way things are.

Can we progress without subject?

We should make a big warning at least.

**Comment by dvm-shlee** [comment] 2021-05-27 01:36
@gdevenyi We could 'force' it with the option if needed, but checking the 'subject' file is the item to validate PVdataset, so removing this validation might cause other unexpected errors of this module.

**Comment by araikes** [comment] 2021-05-28 02:05
Hi @dvm-shlee and @gdevenyi,

So it turns out that the PV360.2 does have the subject top-level file. Those who have been exporting data for me have just been grabbing the scan folders. I am going to hopefully have a complete dataset to test with tomorrow or next week.

**Comment by gdevenyi** [comment] 2021-05-28 03:39
alright! So brkraw is working as expected so far and caught an incomplete dataset. Please confirm that things work properly with a complete dataset and we can close this out with NOTABUG

**Comment by gdevenyi** [comment] 2021-05-28 18:20
>  are critically missing files, like the top-level subject file.

:+1: to this, we should be catching errors for malformed datasets and providing clear feedback on what's wrong if at all possible.

**Comment by araikes** [comment] 2021-06-11 18:50
Hi @gdevenyi and @dvm-shlee ,

I had a chance (finally) to test this with a dataset that includes the subject file. However, I'm still getting the same error about being non-iterable. What else am I missing?

New tar is available here: https://arizona.box.com/s/0viq0v8j2efkcdun4bf94hgaifp3qfwf

```
4/ : T2 RARE
6/ : b1000 shell
7/ : b2000 shell
8/ : b3000 shell
```
Thanks

**Comment by araikes** [comment] 2021-07-13 16:27
Hi @dvm-shlee,
Just a bump on this. I'm still getting non-iterable errors with full exports for PV 360 v2. Anything I can do to fix this?

**Comment by gdevenyi** [comment] 2021-07-13 17:26
Just noticing here, your list goes 2,6,7,8, what about the missing numbers? This is an iteration failure so can you try with a complete export not excluding anything?

**Comment by araikes** [comment] 2021-07-13 19:55
@gdevenyi 

Same issue even with a fully complete export:
https://arizona.box.com/s/m35b627n85gzx6zmrx7m5h3mgr108tpd

**Comment by timrosenow** [comment] 2021-11-16 04:36
Hi all.
I've also had this issue with PV-360.1. I've narrowed down the error a bit, it looks like a problem with this line in utils.py (98)
`is_array = [convert_string_to(c) for c in is_array]`
Using pdb, when the iteration fails, it looks like is_array is actually '[0]' which is automatically converted by `convert_string_to()` to an integer rather than a one-element list.
I haven't worked out what this data actually is yet, but here are the relevant variables at this point in time:

`(Pdb) p is_array
['0']
(Pdb) p data
'@128*(0)'
(Pdb) p shape
' 128 '`

I'm going to add pattern to handle this specific case in `convert_string_to()` and see if that helps resolve the problem.

**Comment by timrosenow** [comment] 2021-11-16 06:08
OK so the problem is deeper than that one call. It looks like maybe the formatting of the metadata files is different in PV360? 

```
File "/usr/local/lib/python3.6/site-packages/brkraw/lib/pvobj.py", line 40, in _update_studyinfo
    self.subj_entry     = get_value(subject, 'SUBJECT_entry').split('_')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by araikes** [comment] 2021-11-16 21:48
@timrosenow,

Try installing the very latest version of `brkraw` from github `pip install git+https://github.com/brkraw/brkraw`.  I recommend a clean conda environment if possible. 

I just tested it an my parsing issues are gone. There are other issues like #66, but `brkraw tonii` works.

**Comment by timrosenow** [comment] 2021-11-19 03:36
@araikes 
Thank you - you are correct, thank you!

**Comment by grandjeanlab** [comment] 2022-01-13 11:05
I think Pull request #80 should solve the issue. Please test and see. I cannot get the dataset through box to test myself.

**Comment by dvm-shlee** [comment] 2022-02-03 02:04
Thank you for helping solve the issue, we tested on the new PV360.v3, so far, working well. I will close this issue

**Closed by dvm-shlee** 2022-02-03 02:04 UTC
