### ISSUE TITLE
brkraw bids converter does not work well with zipped files.

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#38] opened 2021-03-03 18:45 UTC
brkraw bids converter does not work well with zipped files.
On official website:
[Simply put all raw Bruker data (or zipped) into a folder and run ‘brkraw bids_helper’ command](https://brkraw.github.io/docs/gs_bids.html)

Used sample data provided named [bruker2nifti_qa-master.zip, in project readme](https://github.com/BrkRaw/bruker/blob/master/README.md),
1. If supply the zip file directly, bids_helper produced error:
NotADirectoryError: [Errno 20] Not a directory: '/data/zipped/bruker2nifti_qa-master.zip'
2. If supply the parent folder, bids_helper works but produce a blank .xlsx file, which makes the  next step bids converter not converting images.

**Comment by gdevenyi** [comment] 2021-03-03 18:52
The `bruker2nifti_qa-master.zip` file as-is is an image of a git repository and not a single bruker dataset. A single folder from within it zipped up, such as https://gitlab.com/naveau/bruker2nifti_qa/-/tree/master/raw/McGill_Orientation/a20130329_APM_DEV_Orient.j71 should work.

Please test and report back.

**Comment by ycAbout** [comment] 2021-03-04 18:53
Tested used one single data set as you indicated. The same thing happens. 
It works when you unzip all the files, regardless of using the whole qa datasets, or one single dataset. 
This is not a blocker for the usage, but rather a optional feature that has claimed to be working.

**Comment by dvm-shlee** [comment] 2022-02-03 02:54
@gdevenyi I've tested with the file you provided and cannot reproduce the issue.
I think at some point, this issue has been solved

I will close this issue

**Closed by dvm-shlee** 2022-02-03 02:54 UTC
